# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca8343d729c3d627e81c86a3a842d7d1666f6f9844dace3925ec73e64c4daeabdafd8b12f97058ef829f6386f540b8835ae7381c45b7c45eb5091456d8283f0b

test:
  secret_key_base: 60c85ad45c68d2d9ce8093043cd9c10100b19437cb33ba23e61197f13c58824c215aca9f0d11549166c7d8878c78c833963baa7640e1991800f99de1df750891

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
